# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/greeter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/greeter.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"4\n\nAudioReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0ereceived_bytes\x18\x02 \x01(\x03\"I\n\tAudioData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x0c\n\x04rate\x18\x04 \x01(\x05\"\"\n\x12TranscriptionReply\x12\x0c\n\x04text\x18\x01 \x01(\t2\\\n\x07Greeter\x12&\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\x12)\n\x0bStreamAudio\x12\x0b.AudioChunk\x1a\x0b.AudioReply(\x01\x32<\n\x0bTranscriber\x12-\n\nTranscribe\x12\n.AudioData\x1a\x13.TranscriptionReplyB\x16Z\x14grpc-go-python/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024grpc-go-python/proto'
  _globals['_HELLOREQUEST']._serialized_start=23
  _globals['_HELLOREQUEST']._serialized_end=51
  _globals['_HELLOREPLY']._serialized_start=53
  _globals['_HELLOREPLY']._serialized_end=82
  _globals['_AUDIOCHUNK']._serialized_start=84
  _globals['_AUDIOCHUNK']._serialized_end=110
  _globals['_AUDIOREPLY']._serialized_start=112
  _globals['_AUDIOREPLY']._serialized_end=164
  _globals['_AUDIODATA']._serialized_start=166
  _globals['_AUDIODATA']._serialized_end=239
  _globals['_TRANSCRIPTIONREPLY']._serialized_start=241
  _globals['_TRANSCRIPTIONREPLY']._serialized_end=275
  _globals['_GREETER']._serialized_start=277
  _globals['_GREETER']._serialized_end=369
  _globals['_TRANSCRIBER']._serialized_start=371
  _globals['_TRANSCRIBER']._serialized_end=431
# @@protoc_insertion_point(module_scope)
