# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import greeter_pb2 as proto_dot_greeter__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/greeter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """"Greeter"という名前のサービス（機能の集まり）を定義
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/Greeter/SayHello',
                request_serializer=proto_dot_greeter__pb2.HelloRequest.SerializeToString,
                response_deserializer=proto_dot_greeter__pb2.HelloReply.FromString,
                _registered_method=True)
        self.StreamAudio = channel.stream_unary(
                '/Greeter/StreamAudio',
                request_serializer=proto_dot_greeter__pb2.AudioChunk.SerializeToString,
                response_deserializer=proto_dot_greeter__pb2.AudioReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """"Greeter"という名前のサービス（機能の集まり）を定義
    """

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=proto_dot_greeter__pb2.HelloRequest.FromString,
                    response_serializer=proto_dot_greeter__pb2.HelloReply.SerializeToString,
            ),
            'StreamAudio': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=proto_dot_greeter__pb2.AudioChunk.FromString,
                    response_serializer=proto_dot_greeter__pb2.AudioReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """"Greeter"という名前のサービス（機能の集まり）を定義
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Greeter/SayHello',
            proto_dot_greeter__pb2.HelloRequest.SerializeToString,
            proto_dot_greeter__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Greeter/StreamAudio',
            proto_dot_greeter__pb2.AudioChunk.SerializeToString,
            proto_dot_greeter__pb2.AudioReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TranscriberStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/Transcriber/Transcribe',
                request_serializer=proto_dot_greeter__pb2.AudioData.SerializeToString,
                response_deserializer=proto_dot_greeter__pb2.TranscriptionReply.FromString,
                _registered_method=True)


class TranscriberServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """"Transcribe"という名前のRPCを定義
        6秒分の音声データ(AudioData)を一度に受け取り、文字起こし結果(TranscriptionReply)を返す
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriberServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=proto_dot_greeter__pb2.AudioData.FromString,
                    response_serializer=proto_dot_greeter__pb2.TranscriptionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transcriber', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Transcriber', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transcriber(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Transcriber/Transcribe',
            proto_dot_greeter__pb2.AudioData.SerializeToString,
            proto_dot_greeter__pb2.TranscriptionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
